---
driver:
  name: vagrant

provisioner:
  product_name: chef
  product_version: 13

verifier:
  name: inspec

platforms:
  - name: centos-6
  - name: centos-7
  - name: ubuntu-16.04
  - name: amazonlinux-2
    driver:
      box: gbailey/amzn2
      provision: True
      vagrantfiles:
        - al2_workaround.rb

suites:
  - name: default
    run_list:
      - recipe[atop]
    attributes:
      atop:
        interval: 1
